In [1]:
import numpy as np

## Question 2
### Part A: Fractional Coordinates

Create numpy arrays representing the fractional coordinates of leu50 

In [2]:
raw_leu50 = np.array([38.093, 2.505, 53.400])
unit_cell_dim = np.array([94, 94, 82.1])

In [3]:
frac_leu50 = raw_leu50 / unit_cell_dim

In [4]:
frac_leu50

array([0.40524468, 0.02664894, 0.65042631])

Tuple representing the fractional coordinates of leu50 

In [13]:
leu50_tuple = (0.40524468, 0.02664894, 0.65042631)

### Part B: Symmetry Operations

Create variables for the 8 different symmetry operations available 

In [11]:
op1 = lambda x, y, z: (x, y, z)
op2 = lambda x, y, z: (-x, -y, 0.5 + z)
op3 = lambda x, y, z: (0.5-y,0.5+x,0.75+z)
op4 = lambda x, y, z: (0.5+y,0.5-x,0.25+z)
op5 = lambda x, y, z: (y,x,-z)
op6 = lambda x, y, z: (-y,-x,0.5-z)
op7 = lambda x, y, z: (0.5-x,0.5+y,0.75-z) 
op8 = lambda x, y, z: (0.5+x,0.5-y,0.25-z)

Generate corresponding atoms based on reference leu50 

In [36]:
atom_coordinates = [op1(0.40524468, 0.02664894, 0.65042631),
                    op2(0.40524468, 0.02664894, 0.65042631),
                    op3(0.40524468, 0.02664894, 0.65042631),
                    op4(0.40524468, 0.02664894, 0.65042631),
                    op5(0.40524468, 0.02664894, 0.65042631),
                    op6(0.40524468, 0.02664894, 0.65042631),
                    op7(0.40524468, 0.02664894, 0.65042631),
                    op8(0.40524468, 0.02664894, 0.65042631)]
atom_coordinates

[(0.40524468, 0.02664894, 0.65042631),
 (-0.40524468, -0.02664894, 1.1504263099999998),
 (0.47335106, 0.90524468, 1.4004263099999998),
 (0.52664894, 0.09475531999999998, 0.90042631),
 (0.02664894, 0.40524468, -0.65042631),
 (-0.02664894, -0.40524468, -0.15042630999999995),
 (0.09475531999999998, 0.52664894, 0.09957369000000005),
 (0.90524468, 0.47335106, -0.40042630999999995)]

Change the data type of the atom coordinates into a numpy array for ease of use below 

In [37]:
atom_coordinates_array = np.array(atom_coordinates)
atom_coordinates_array

array([[ 0.40524468,  0.02664894,  0.65042631],
       [-0.40524468, -0.02664894,  1.15042631],
       [ 0.47335106,  0.90524468,  1.40042631],
       [ 0.52664894,  0.09475532,  0.90042631],
       [ 0.02664894,  0.40524468, -0.65042631],
       [-0.02664894, -0.40524468, -0.15042631],
       [ 0.09475532,  0.52664894,  0.09957369],
       [ 0.90524468,  0.47335106, -0.40042631]])

In [38]:
atom_coordinates_array[2]

array([0.47335106, 0.90524468, 1.40042631])

Create a for loop that adjusts atom coordinates so that there are none < 0 or > 1 

In [40]:
adj_atom_coordinates = atom_coordinates_array

for row in range(0, 8):
    for col in range(0,3):
        
        if atom_coordinates_array[row, col] < 0:
            adj_atom_coordinates[row, col] = 1 - abs(atom_coordinates_array[row, col])
            
        elif atom_coordinates_array[row, col] > 1:
            adj_atom_coordinates[row, col] = atom_coordinates_array[row, col] - 1
            
        else:
            adj_atom_coordinates[row, col] = atom_coordinates_array[row, col]


Display the final set representing the coordinates of each atom in each row 

In [41]:
adj_atom_coordinates

array([[0.40524468, 0.02664894, 0.65042631],
       [0.59475532, 0.97335106, 0.15042631],
       [0.47335106, 0.90524468, 0.40042631],
       [0.52664894, 0.09475532, 0.90042631],
       [0.02664894, 0.40524468, 0.34957369],
       [0.97335106, 0.59475532, 0.84957369],
       [0.09475532, 0.52664894, 0.09957369],
       [0.90524468, 0.47335106, 0.59957369]])

## Question 3
### Part A: Structure Factor 

In [108]:
miller_indices = [1,5,2]
frac_coords = (0.1, 0.3 ,0.7)
scat_fac = 34

Create a list of symmetry operators for the space group P21212 

In [109]:
p21212_operators = [lambda x, y, z: (x, y, z),
                    lambda x, y, z: (-x, -y, z),
                    lambda x, y, z: (0.5 - x, 0.5 + y, -z),
                    lambda x, y, z: (0.5 + x, 0.5 - y, -z )]

Use the symmetry oeprators to find coordinates for the other atoms in the unit cell 

In [110]:
all_atoms = [p21212_operators[0](0.1, 0.3 ,0.7),
             p21212_operators[1](0.1, 0.3 ,0.7),
             p21212_operators[2](0.1, 0.3 ,0.7),
             p21212_operators[3](0.1, 0.3 ,0.7)]
all_atoms

[(0.1, 0.3, 0.7), (-0.1, -0.3, 0.7), (0.4, 0.8, -0.7), (0.6, 0.2, -0.7)]

Change coordinates into a numpy array 

In [111]:
atom_coordinates_array = np.array(all_atoms)
atom_coordinates_array

array([[ 0.1,  0.3,  0.7],
       [-0.1, -0.3,  0.7],
       [ 0.4,  0.8, -0.7],
       [ 0.6,  0.2, -0.7]])

Same for loop as above 

In [112]:
atom_coordinates_array = np.array(all_atoms)
adj_atom_coordinates = atom_coordinates_array

for row in range(0, 4):
    for col in range(0,3):
        
        if atom_coordinates_array[row, col] < 0:
            adj_atom_coordinates[row, col] = 1 - abs(atom_coordinates_array[row, col])
            
        elif atom_coordinates_array[row, col] > 1:
            adj_atom_coordinates[row, col] = atom_coordinates_array[row, col] - 1
            
        else:
            adj_atom_coordinates[row, col] = atom_coordinates_array[row, col]

The final adjusted coordinates. 

In [113]:
adj_atom_coordinates

array([[0.1, 0.3, 0.7],
       [0.9, 0.7, 0.7],
       [0.4, 0.8, 0.3],
       [0.6, 0.2, 0.3]])

In [114]:
import math

Create two functions, one for the real part of the structure factor function and one for the imaginary part 

In [115]:
real_structure_factor_function = lambda x, y, z, h, k, l: 34 * math.cos(2*np.pi*(h*x + k*y + l*z))
imag_structure_factor_function = lambda x, y, z, h, k, l: 34 * math.sin(2*np.pi*(h*x + k*y + l*z))

Calculate the terms in the sum 

In [116]:
real_factor_terms = [real_structure_factor_function(0.1, 0.3, 0.7, 1, 5, 2),
                     real_structure_factor_function(0.9, 0.7, 0.7, 1, 5, 2),
                     real_structure_factor_function(0.4, 0.8, 0.3, 1, 5, 2),
                     real_structure_factor_function(0.6, 0.2, 0.3, 1, 5, 2)]

imag_factor_terms = [imag_structure_factor_function(0.1, 0.3, 0.7, 1, 5, 2),
                     imag_structure_factor_function(0.9, 0.7, 0.7, 1, 5, 2),
                     imag_structure_factor_function(0.4, 0.8, 0.3, 1, 5, 2),
                     imag_structure_factor_function(0.6, 0.2, 0.3, 1, 5, 2)]

In [117]:
imag_factor_terms

[-2.4982794702606005e-14,
 -32.33592155403517,
 -4.1637991171010013e-14,
 32.33592155403524]

### Part B: Argand Diagram Cordinates

Calculate the sum of the terms above and thus the value of the real and imaginary parts of the structure factor 

In [118]:
real_structure_factor = np.array(real_factor_terms).sum()
imag_structure_factor = np.array(imag_factor_terms).sum()

print(real_structure_factor, imag_structure_factor)

(89.01315561749658, 0.0)


### Part C: Intensity of the (1,5,2) reflection

In [119]:
intensity = np.power(real_structure_factor, 2) + np.power(imag_structure_factor, 2)
intensity

7923.341872984663

### Part D: F(0,5,0)

Same thing as above but with F(0,5,0)  

In [120]:
real_structure_factor_function = lambda x, y, z, h, k, l: 34 * math.cos(2*np.pi*(h*x + k*y + l*z))
imag_structure_factor_function = lambda x, y, z, h, k, l: 34 * math.sin(2*np.pi*(h*x + k*y + l*z))

In [121]:
real_factor_terms = [real_structure_factor_function(0.1, 0.3, 0.7, 0, 5, 0),
                     real_structure_factor_function(0.9, 0.7, 0.7, 0, 5, 0),
                     real_structure_factor_function(0.4, 0.8, 0.3, 0, 5, 0),
                     real_structure_factor_function(0.6, 0.2, 0.3, 0, 5, 0)]

imag_factor_terms = [imag_structure_factor_function(0.1, 0.3, 0.7, 0, 5, 0),
                     imag_structure_factor_function(0.9, 0.7, 0.7, 0, 5, 0),
                     imag_structure_factor_function(0.4, 0.8, 0.3, 0, 5, 0),
                     imag_structure_factor_function(0.6, 0.2, 0.3, 0, 5, 0)]

In [122]:
real_structure_factor = np.array(real_factor_terms).sum()
imag_structure_factor = np.array(imag_factor_terms).sum()

print(real_structure_factor, imag_structure_factor)

(0.0, 1.5777218104420236e-30)


In [123]:
intensity = np.power(real_structure_factor, 2) + np.power(imag_structure_factor, 2)
intensity

2.4892061111444567e-60

## Question 4

In [152]:
miller_indices = [3,7,1]
frac_coords = (0.15, 0.21 ,0.34)
scat_fac = 80
native_I = 32000
derivative_I = 40000
unit_cell_dims = [135.0, 37.3, 49.0]

Create a list of symmetry operators for the space group P21212 

In [153]:
p21212_operators = [lambda x, y, z: (x, y, z),
                    lambda x, y, z: (-x, -y, z),
                    lambda x, y, z: (0.5 - x, 0.5 + y, -z),
                    lambda x, y, z: (0.5 + x, 0.5 - y, -z )]

In [154]:
all_atoms = [p21212_operators[0](0.15, 0.21 ,0.34),
             p21212_operators[1](0.15, 0.21 ,0.34),
             p21212_operators[2](0.15, 0.21 ,0.34),
             p21212_operators[3](0.15, 0.21 ,0.34)]
all_atoms

[(0.15, 0.21, 0.34),
 (-0.15, -0.21, 0.34),
 (0.35, 0.71, -0.34),
 (0.65, 0.29000000000000004, -0.34)]

In [155]:
atom_coordinates_array = np.array(all_atoms)
atom_coordinates_array

array([[ 0.15,  0.21,  0.34],
       [-0.15, -0.21,  0.34],
       [ 0.35,  0.71, -0.34],
       [ 0.65,  0.29, -0.34]])

In [156]:
atom_coordinates_array = np.array(all_atoms)
adj_atom_coordinates = atom_coordinates_array

for row in range(0, 4):
    for col in range(0,3):
        
        if atom_coordinates_array[row, col] < 0:
            adj_atom_coordinates[row, col] = 1 - abs(atom_coordinates_array[row, col])
            
        elif atom_coordinates_array[row, col] > 1:
            adj_atom_coordinates[row, col] = atom_coordinates_array[row, col] - 1
            
        else:
            adj_atom_coordinates[row, col] = atom_coordinates_array[row, col]

In [157]:
adj_atom_coordinates

array([[0.15, 0.21, 0.34],
       [0.85, 0.79, 0.34],
       [0.35, 0.71, 0.66],
       [0.65, 0.29, 0.66]])

In [158]:
real_structure_factor_function = lambda x, y, z, h, k, l: 80 * math.cos(2*np.pi*(h*x + k*y + l*z))
imag_structure_factor_function = lambda x, y, z, h, k, l: 80 * math.sin(2*np.pi*(h*x + k*y + l*z))

In [159]:
real_factor_terms = [real_structure_factor_function(0.15, 0.21, 0.34, 3, 7, 1),
                     real_structure_factor_function(0.85, 0.79, 0.34, 3, 7, 1),
                     real_structure_factor_function(0.35, 0.71, 0.66, 3, 7, 1),
                     real_structure_factor_function(0.65, 0.29, 0.66, 3, 7, 1)]

imag_factor_terms = [imag_structure_factor_function(0.15, 0.21, 0.34, 3, 7, 1),
                     imag_structure_factor_function(0.85, 0.79, 0.34, 3, 7, 1),
                     imag_structure_factor_function(0.35, 0.71, 0.66, 3, 7, 1),
                     imag_structure_factor_function(0.65, 0.29, 0.66, 3, 7, 1)]

In [160]:
real_structure_factor = np.array(real_factor_terms).sum()
imag_structure_factor = np.array(imag_factor_terms).sum()

print(real_structure_factor, imag_structure_factor)

(-160.18403847095533, -15.644791416945253)


In [148]:
alpha_heavy = math.atan(imag_structure_factor / real_structure_factor)
alpha_heavy = np.pi + alpha_heavy
alpha_heavy

3.238951474923198

In [161]:
intensity = np.power(real_structure_factor, 2) + np.power(imag_structure_factor, 2)
intensity

25903.68567934422